[project]
name = "genesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "kagglehub>=0.3.13",
    "notebook>=7.4.7",
    "torch",
    "torchvision",
]
